# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20160714_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdiscount',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='productdiscount',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='actual_price',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[(b'AP', b'Allo Paratha'), (b'PP', b'Pyaz Paratha')], default=1, max_length=2, verbose_name='Product Subcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[(b'SNC', b'Snacks'), (b'PRT', b'Paratha'), (b'BRG', b'Burgers'), (b'SNW', b'Sandwiches'), (b'BVR', b'Beverages'), (b'CHP', b'Chips')], max_length=2, verbose_name='Product Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='Product Rating'),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='ProductDiscount',
        ),
    ]
