# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20160814_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='Product Unique ID'),
        ),
    ]
