# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20160820_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[(b'PRT', b'Paratha'), (b'MGG', b'Maggie'), (b'BRG', b'Burger'), (b'SNW', b'Sandwich'), (b'TST', b'Toast'), (b'BVR', b'Beverage'), (b'OTH', b'Other')], max_length=3, verbose_name='Product Category'),
        ),
    ]
