# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20160820_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='logo',
            field=models.FileField(upload_to=products.models.product_logo_upload, verbose_name='Product Logo'),
        ),
    ]
