# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 15:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(verbose_name='Feedback/Comment')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Feedback Given At')),
                ('delete', models.BooleanField(default=False, verbose_name='Delete')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='ProductFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(verbose_name='Product Rating')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_feed', to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productfeed_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ProductFeedback',
                'verbose_name_plural': 'ProductFeedbacks',
            },
        ),
        migrations.CreateModel(
            name='ProductOrderTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='Ordered At')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_track', to='products.Product')),
            ],
            options={
                'verbose_name': 'ProductOrderTrack',
                'verbose_name_plural': 'ProductOrderTracks',
            },
        ),
    ]
