# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 15:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Product Quantity')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total Amount')),
                ('delivery_status', models.CharField(choices=[('1', 'Order Confirmed'), ('2', 'In Progress'), ('3', 'Order Delivered'), ('4', 'Order Cancelled')], default='1', max_length=1, verbose_name='Delivery Status')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='Order Placed At')),
                ('delivery_at', models.DateTimeField(verbose_name='Order Delivery At')),
                ('delete', models.BooleanField(default=False, verbose_name='Delete')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='products.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ordered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
