# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-14 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20160814_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='pid',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Cart Session Product ID'),
        ),
        migrations.AddField(
            model_name='cart',
            name='uid',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Cart Session unique ID'),
        ),
    ]
