# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20160814_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='pid',
            field=models.CharField(default=1, max_length=90, verbose_name='Cart Session Product ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='uid',
            field=models.CharField(default=1, max_length=90, verbose_name='Cart Session unique ID'),
            preserve_default=False,
        ),
    ]
